
NAME :=			checker

SRC_PATH :=		./
COMMON_PATH :=	../push_swap/
INC_PATH :=		../../includes/
LIB_PATH :=		../../libft/
OBJ_PATH :=		.obj/push_swap/

CC :=			clang
CFLAGS :=		-g -Wall -Werror -Wextra
IFLAGS :=		-I $(INC_PATH) -I $(LIB_PATH)
LFLAGS :=		-lft -L $(LIB_PATH)

LIB :=			$(LIB_PATH)libft.a
HFILES :=		push_swap
FILES :=		checker
COMMON_FILES :=	lists_op manage_op funcional

HDRS :=			$(addprefix $(INC_PATH), $(addsuffix .h, $(HFILES)))
SRCS +=			$(addprefix $(SRC_PATH), $(addsuffix .c, $(FILES)))
SRCS +=			$(addprefix $(COMMON_PATH), $(addsuffix .c, $(COMMON_FILES)))
OBJS :=			$(addprefix $(OBJ_PATH), $(SRCS:%.c=%.o))


all: $(NAME)

$(NAME): $(LIB) $(OBJ_PATH) $(OBJS)
	@ $(CC) $(CFLAGS) $(IFLAGS) $(LFLAGS) $(OBJS) -o $(NAME)
$(LIB):
	@ $(MAKE) -C $(dir $@) $(notdir $@)

$(OBJ_PATH):
	mkdir -p $(OBJ_PATH)$(SRC_PATH)
$(OBJ_PATH)%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) $(IFLAGS) -c $< -o $@

clean: mclean
	make clean -C $(LIB_PATH)
fclean: mfclean
	make fclean -C $(LIB_PATH)
re: fclean all

mclean:
	rm -f $(OBJS) $(DEPS)
mfclean:
	rm -f $(NAME)
	rm -rf $(OBJ_PATH)
mre: mfclean all

.PHONY: $(LIB) all clean fclean re mclean mfclean mre
